Задание 2.5. Итерация по массивам
htmlacademy-php/2080485-readme-12 pull request #3
Opened 2022-04-24 17:47 UTC by aikrasnov

2022-04-25 11:22 UTC, sterlikoff requested changes
Александр, вставил скрипт в верстку хорошо, но ошибся немного: посты должны выглядеть как в макете: http://joxi.ru/brRaXd0H79kgvA. У тебя сейчас вот так: http://joxi.ru/eAOL35gu9BnNOr

`<article>` тоже должен быть внутри `foreach`.

2022-04-25 18:48 UTC, akrasnov-marfatech commented
Да, тоже подумал, что это странно выглядит :) Поправим!

2022-04-25 18:56 UTC, akrasnov-marfatech commented
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/92787457/165155487-c32b5a64-4d87-4024-a017-d760e59f0851.png">
Поправил.

2022-04-26 13:27 UTC, sterlikoff approved these changes
Александр, отлично, теперь как надо :)
Зачет, идем дальше!

2022-04-26 13:27 UTC, merged